spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/summer?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# swagger
swagger:
  enabled: true








